**Basics of NumPy (Numerical Python)**


In [4]:
#import thr numpy package
import numpy as np

# Create a 1d integer array from a list
arr1 = np.array([1,2,3,4,5])

#printing the arr1
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#creating 1d float array
arr2 = np.array([1,2,3,4,5.123], dtype='float32')

print(arr2)
print(type(arr2))


[1.    2.    3.    4.    5.123]
<class 'numpy.ndarray'>


In [8]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)

# Vector (element-wise) operations
print(arr1 * 2)
print(arr1 + 2)
print(arr1 * arr1)

[1 2 3 4]
[2 4 6 8]
[3 4 5 6]
[ 1  4  9 16]


In [13]:
# Create an integer array of length 10 filled with zeros
arr_0 = np.zeros(10, dtype=int)
print("array with zeros" ,arr_0)

# Create a 3x3 floating-point array filled with 1s
arr_1 = np.ones((3, 3), dtype=float)
print(arr_1)

# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 3
# (this is similar to the built-in range() function)
np.arange(0, 20, 3)

# Create an array of hundred values evenly spaced between 0 and 1
np.linspace(0, 1, 100)

# Create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3, 3))

# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

np.random.randint(10, size=6)  # One-dimensional array of random integers
np.random.randint(10, size=(3, 3))  # Two-dimensional array of random integers
np.random.randint(10, size=(3, 3, 3))  # Three-dimensional array of random integers

array with zeros [0 0 0 0 0 0 0 0 0 0]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array([[[3, 9, 7],
        [0, 4, 2],
        [8, 2, 5]],

       [[6, 7, 4],
        [8, 5, 6],
        [3, 0, 6]],

       [[1, 7, 5],
        [4, 1, 1],
        [8, 3, 8]]])

In [14]:
import numpy as np

# Create a 3x3 array of random integers in the interval [0, 10)
x = np.random.randint(0, 10, (3, 3))

print("ndim: ", x.ndim)
print("shape:", x.shape)
print("x size: ", x.size)
print("dtype:", x.dtype)
print("itemsize:", x.itemsize, "bytes")
print("nbytes:", x.nbytes, "bytes")

ndim:  2
shape: (3, 3)
x size:  9
dtype: int64
itemsize: 8 bytes
nbytes: 72 bytes
